// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYLZnvtG8iFtCKAy2RuwEEZSbflqtQtVc',
    appId: '1:723579587687:web:e33d3811353bc1030298c2',
    messagingSenderId: '723579587687',
    projectId: 'airpay-app',
    authDomain: 'airpay-app.firebaseapp.com',
    storageBucket: 'airpay-app.appspot.com',
    measurementId: 'G-FW3Q93F7H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrsZ-ylgudRTghWYAQsc-Q9NByVz0uJ-I',
    appId: '1:723579587687:android:d49c542dbc1770c20298c2',
    messagingSenderId: '723579587687',
    projectId: 'airpay-app',
    storageBucket: 'airpay-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8zBGED2d7xvKXG8lty6pM93-ZFmglEM',
    appId: '1:723579587687:ios:973ec356f0707d040298c2',
    messagingSenderId: '723579587687',
    projectId: 'airpay-app',
    storageBucket: 'airpay-app.appspot.com',
    iosClientId: '723579587687-uaa0rg8cg2juplmvarlb7abgtvkkk5ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.airpay',
  );
}
